name: CI (Lint, Typecheck, Test & Build)

on:
  pull_request:
    branches: ["main"]

jobs:
  build-lint-test:
    name: Build, Lint, Typecheck, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - run: corepack enable

      - run: corepack npm ci

      - run: corepack npm run lint

      - run: corepack npm run typecheck

      - name: Test
        run: corepack npm test

      - name: Build
        run: corepack npm run build
